name: Build & Push Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: cr.yandex/crppthgv7553krfpenjf/diploma-app
  FOLDER_ID: b1gi750rb0rc8mjglafr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Configure YC
        run: |
          echo '${{ secrets.YC_SA_KEY }}' > key.json
          yc config set service-account-key key.json
          yc config set folder-id ${{ env.FOLDER_ID }}

      - name: Docker Login
        run: |
          echo '${{ secrets.YC_SA_KEY }}' > key.json
          cat key.json | docker login \
            --username json_key \
            --password-stdin cr.yandex
      - name: Determine tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: |
          docker build -t ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }} .

      - name: Push
        run: |
          docker push ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }}
