---
name: Build & Push Image

'on':
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: cr.yandex/crprb0be03l7semd3i14/diploma-app
  FOLDER_ID: b1gi750rb0rc8mjglafr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Setup YC CLI
        uses: yandex-cloud/actions/setup-yc@v1
        with:
          yc-service-account-key: ${{ secrets.YC_SA_KEY }}
          yc-folder-id: ${{ env.FOLDER_ID }}

      - name: Build & Push
        run: |
          yc container registry configure-docker
          docker build -t ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }} .
          docker push ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }}
