---
name: Build & Push Image

'on':
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: cr.yandex/crppthgv7553krfpenjf/diploma-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Install YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Login to YCR
        run: |
          printf '%s\n' '${{ secrets.YC_SA_KEY }}' > /tmp/yc-key.json
          yc config profile create ci
          yc config set service-account-key /tmp/yc-key.json
          TOKEN=$(yc iam create-token)
          docker login -u iam -p "$TOKEN" cr.yandex
          rm -f /tmp/yc-key.json

      - name: Build & Push
        run: |
          docker build -t ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }} .
          docker push ${{ env.REGISTRY }}:${{ steps.tag.outputs.TAG }}
